name: Build site and serve with GitHub Pages

on:
  push:
    branches:
      - main

env:
# Didn't name it 'docs' to avoid any (unlikely) confusion when setting up directory to run GithubPages from
  DOC_BRANCH: documentation

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Uses main Branch
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Setup Git
      run: |
        git config --local user.name  taennan
        git config --local user.email taennan@zohomail.com

    - name: Create Doc Branch
      run: git checkout -b gh-pages

    - name: Build Website
      run: yarn install && yarn build

    - name: Remove Unecessary Files
      run: |
        rm -rf  .github \
                src \
                public \
                index.html \
                package.json \
                yarn.lock \
                svelte.config.js \
                vite.config.ts \
                tsconfig.json \
                tsconfig.node.json

    # Have to do this after removing other files due to collisions with index.html
    - name: Move built files into root
      run: |
        mv dist/* ./
        rmdir dist

    - name: Commit and Deploy
      run: |
        git add .
        git commit -m 'rebuilt website'
        git push -f --set-upstream origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
